name: geomesher-tests
channels:
- conda-forge
- nodefaults
dependencies:
- numpy
- pandas
- geopandas-base
- gmsh
- python-gmsh
- scipy
- shapely >=2.0

# test deps
- psutil
- pytest-cov
- pytest-xdist
